# This file configures the analyzer, which statically analyzes Dart code.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - ".dart_tool/**"
    - "linux/**"
    - "android/**"
    - "ios/**"
    - "windows/**"
    - "web/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # avoid_print: false
